name: xEssentials
version: 1.1
description: a
author: Xeph0re
authors: [] 
website:

main: tv.mineinthebox.xEssentials
database: false
depend: []
softdepend: [WorldGuard, WorldEdit, Votifier, Vault, iConomy, RemoteEntities]

commands:
  sethome:
     description: allows you to set your home
     aliases: []
     permission:
     permission-message:

  home:
     description: allows you to teleport to home
     aliases: []
     permission:
     permission-message:

  setspawn:
     description: allows you to teleport to set the spawn
     aliases: []
     permission:
     permission-message:

  spawn:
     description: allows you to teleport to the spawn
     aliases: []
     permission:
     permission-message:

  vanish:
     description: vanish yourself
     aliases: [v]
     permission:
     permission-message:

  firefly:
     description: firefly
     aliases: []
     permission:
     permission-message:

  spawner:
     description: change spawners
     aliases: []
     permission:
     permission-message:

  gamemode:
     description: change gamemode
     aliases: [gm]
     permission:
     permission-message:

  modreq:
     description: create a modreq
     aliases: []
     permission:
     permission-message:

  spawnmob:
     description: spawnmobs
     aliases: []
     permission:
     permission-message:

  warp:
     description: warp command
     aliases: []
     permission:
     permission-message:

  setwarp:
     description: setwarp command
     aliases: []
     permission:
     permission-message:

  invsee:
     description: open a other players inventory
     aliases: []
     permission:
     permission-message:

  torch:
     description: torch command
     aliases: []
     permission:
     permission-message:

  warps:
     description: shows warp list
     aliases: []
     permission:
     permission-message:

  delwarp:
     description: delete a warp
     aliases: []
     permission:
     permission-message:

  ban:
     description: ban a player
     aliases: []
     permission:
     permission-message:

  unban:
     description: unbans a player
     aliases: [pardon]
     permission:
     permission-message:

  tempban:
     description: tempbans a player
     aliases: [tmpban, tb]
     permission:
     permission-message:

  claim:
     description: claims a modreq
     aliases: []
     permission:
     permission-message:

  check:
     description: check your own modreq request
     aliases: []
     permission:
     permission-message:

  done:
     description: close a modreq
     aliases: []
     permission:
     permission-message:

  teleport:
     description: teleport
     aliases: [tele, tp]
     permission:
     permission-message:

  hometp:
     description: hometp
     aliases: [htp]
     permission:
     permission-message:

  tphere:
     description: teleports a player to your location
     aliases: [th]
     permission:
     permission-message:

  tpa:
     description: tpa
     aliases: []
     permission:
     permission-message:

  tpahere:
     description: tpahere
     aliases: []
     permission:
     permission-message:

  fly:
     description: fly mode
     aliases: []
     permission:
     permission-message:

  mute:
     description: mute a player
     aliases: []
     permission:
     permission-message:

  unmute:
     description: unmute a player
     aliases: []
     permission:
     permission-message:

  xessentials:
     description: default plugin command
     aliases: []
     permission:
     permission-message:

  gc:
     description: garbage collector mode
     aliases: []
     permission:
     permission-message:

  homeinvite:
     description: invite a player to your home
     aliases: []
     permission:
     permission-message:

  back:
     description: teleport back to your last location
     aliases: []
     permission:
     permission-message:

  spawnherobrine:
     description: ???
     aliases: []
     permission:
     permission-message:

  broadcast:
     description: broadcast management
     aliases: []
     permission:
     permission-message:


permissions:
  #supertowns.random:
  #  description: Gives access to all plugin commands
  #  children:
  #    supertowns.randomSuper: true