name: xEssentials
version: 1.1
description: a
author: Xeph0re
authors: [] 
website:

main: tv.mineinthebox.xEssentials
database: false
depend: []
softdepend: [WorldGuard, WorldEdit, Votifier, Vault, iConomy]

commands:
  sethome:
     description: allows you to set your home
     aliases: []
     permission:
     permission-message:

  home:
     description: allows you to teleport to home
     aliases: []
     permission:
     permission-message:

  setspawn:
     description: allows you to teleport to set the spawn
     aliases: []
     permission:
     permission-message:

  spawn:
     description: allows you to teleport to the spawn
     aliases: []
     permission:
     permission-message:

  vanish:
     description: vanish yourself
     aliases: [v]
     permission:
     permission-message:

  firefly:
     description: firefly
     aliases: []
     permission:
     permission-message:

  spawner:
     description: change spawners
     aliases: []
     permission:
     permission-message:

  gamemode:
     description: change gamemode
     aliases: []
     permission:
     permission-message:

permissions:
  #supertowns.random:
  #  description: Gives access to all plugin commands
  #  children:
  #    supertowns.randomSuper: true