name: xEssentials
version: 1.1
description: a
author: Xeph0re
authors: [] 
website:

main: tv.mineinthebox.xEssentials
database: false
depend: []
softdepend: [WorldGuard, WorldEdit, Votifier, Vault, iConomy]

commands:
  sethome:
     description: allows you to set your home
     aliases: []
     permission:
     permission-message:

  home:
     description: allows you to teleport to home
     aliases: []
     permission:
     permission-message:

permissions:
  #supertowns.random:
  #  description: Gives access to all plugin commands
  #  children:
  #    supertowns.randomSuper: true